services:
  - type: web
    name: dungeon-of-the-forgotten-king
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TERM
        value: xterm-256color
